name: Create Golden AMI and Push to AWS

on:
  workflow_dispatch:
    inputs:
      amiId:
        description: 'The source AMI ID (for example ami-03f8756d29f0b5f21, regional specific) used to build the AMI'
        required: true
      ssh_username:
        description: 'The ssh username of above AMI'
      regionName:
        description: 'The region (for example us-west-2) where Packer is building the AMI.'
        required: true
      description:
        description: 'The description of building the AMI pipeline (will be sent to slack channels)'
        default: ''
        required: false

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.regionName }}

      - name: Packer Init
        run: packer init ./packer-build/packer-version.pkr.hcl

      - name: Packer Build
        run: |
          packer validate ./packer-build/amazon-ebs-build.pkr.hcl
          packer build -var aws_ami_id=${{ github.event.inputs.amiId }} -var ssh_username=${{github.event.inputs.ssh_username}} -var aws_region=${{ github.event.inputs.regionName }} ./packer-build/amazon-ebs-build.json.pkr.hcl
